name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO111MODULE: on

permissions:
  contents: read

jobs:


  lic-headers:
    runs-on: ubuntu-26.04
    steps:

      - uses: actions/checkout@v7

      - run: >-
          docker run
          -v $(pwd):/wrk -w /wrk
          ghcr.io/google/addlicense
          -c 'The Cobra Authors'
          -y '2013-2023'
          -l apache
          -ignore '.github/**'
          -check
          .


  golangci-lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    runs-on: ubuntu-26.04
    steps:

      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --verbose


  test-unix:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-26.04
        - xcode-27
    name: '${{ matrix.os }} | go.mod'
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v7

    - uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
        check-latest: true
        cache: true

    - run: |
        export GOBIN=$HOME/go/bin
        go install github.com/kyoh86/richgo@latest

    - run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH make richtest


  test-win:
    name: 'windows-2025 | go.mod'
    runs-on: windows-2025
    steps:

    - shell: bash
      run: git config --global core.autocrlf input

    - uses: actions/checkout@v7

    - uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
        check-latest: true

    - shell: bash
      run: go install github.com/kyoh86/richgo@latest

    - shell: bash
      run: RICHGO_FORCE_COLOR=1 richgo test -v ./...
